development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: ongaku_ryoho_development
  pool: 5
  username: purplesynth
  password: hello

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: ongaku_ryoho_test
  pool: 5
  username: purplesynth
  password: hello

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
