defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: ongaku_ryoho_development

test:
  <<: *defaults
  database: ongaku_ryoho_test

production:
  <<: *defaults
  database: ongaku_ryoho
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
